/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tabletennisscores; // Match scores imported via an external text file

import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Adam Matheson
 */
public class TTScoreGUI1 extends javax.swing.JFrame {

    /**
     * Creates new form TTScoreGUI1
     */
    public TTScoreGUI1() {
        initComponents();
        //my own objects for registration, matches and reports

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") //Create UI, setup elements, layouts, properties etc.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel100 = new javax.swing.JPanel();
        setPanel = new javax.swing.JPanel();
        set11 = new javax.swing.JTextField();
        gamePanel1 = new javax.swing.JPanel();
        set11ahpts = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        set11aapts = new javax.swing.JTextField();
        gamePanel2 = new javax.swing.JPanel();
        set11bhpts = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        set11bapts = new javax.swing.JTextField();
        gamePanel = new javax.swing.JPanel();
        set11chpts = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        set11capts = new javax.swing.JTextField();
        setPanel1 = new javax.swing.JPanel();
        setDbl = new javax.swing.JTextField();
        gamePanel3 = new javax.swing.JPanel();
        dah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        daa = new javax.swing.JTextField();
        gamePanel4 = new javax.swing.JPanel();
        dbh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dba = new javax.swing.JTextField();
        gamePanel5 = new javax.swing.JPanel();
        dch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        setPanel2 = new javax.swing.JPanel();
        set12 = new javax.swing.JTextField();
        gamePanel6 = new javax.swing.JPanel();
        set12ahpts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        set12aapts = new javax.swing.JTextField();
        gamePanel7 = new javax.swing.JPanel();
        set12bhpts = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        set12bapts = new javax.swing.JTextField();
        gamePanel8 = new javax.swing.JPanel();
        set12chpts = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        set12capts = new javax.swing.JTextField();
        setPanel3 = new javax.swing.JPanel();
        set22 = new javax.swing.JTextField();
        gamePanel9 = new javax.swing.JPanel();
        set22ahpts = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        set22aapts = new javax.swing.JTextField();
        gamePanel10 = new javax.swing.JPanel();
        set22bhpts = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        set22bapts = new javax.swing.JTextField();
        gamePanel11 = new javax.swing.JPanel();
        set22chpts = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        set22capts = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        setPanel4 = new javax.swing.JPanel();
        set21 = new javax.swing.JTextField();
        gamePanel12 = new javax.swing.JPanel();
        set21ahpts = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        set21aapts = new javax.swing.JTextField();
        gamePanel13 = new javax.swing.JPanel();
        set21bhpts = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        set21bapts = new javax.swing.JTextField();
        gamePanel14 = new javax.swing.JPanel();
        set21chpts = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        set21capts = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        aPlayer1 = new javax.swing.JTextField();
        aPlayer2 = new javax.swing.JTextField();
        hPlayer1 = new javax.swing.JTextField();
        hPlayer2 = new javax.swing.JTextField();
        calScorebutton = new javax.swing.JButton();
        hdblplayer1 = new javax.swing.JTextField();
        hdblplayer2 = new javax.swing.JTextField();
        adblplayer1 = new javax.swing.JTextField();
        adblplayer2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        hWinRow1 = new javax.swing.JLabel();
        doubleHWin = new javax.swing.JLabel();
        hWinTotal = new javax.swing.JLabel();
        hWinRow2 = new javax.swing.JLabel();
        aWinRow1 = new javax.swing.JLabel();
        aWinRow2 = new javax.swing.JLabel();
        doubleAWin = new javax.swing.JLabel();
        aWinTotal = new javax.swing.JLabel();
        submitScoreButton = new javax.swing.JButton();
        newMatchButton = new javax.swing.JButton();
        hTeamName = new javax.swing.JLabel();
        aTeamName = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        hTeamField = new javax.swing.JTextField();
        aTeamField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        testScoreButton = new javax.swing.JButton();
        allTeamButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        set11.setText("set number");
        set11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set11ActionPerformed(evt);
            }
        });

        set11ahpts.setColumns(5);
        set11ahpts.setText("0");
        set11ahpts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set11ahptsActionPerformed(evt);
            }
        });

        jLabel2.setText(":");

        set11aapts.setColumns(5);
        set11aapts.setText("0");
        set11aapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set11aaptsActionPerformed(evt);
            }
        });

        set11bhpts.setColumns(5);
        set11bhpts.setText("0");

        jLabel3.setText(":");

        set11bapts.setColumns(5);
        set11bapts.setText("0");
        set11bapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set11baptsActionPerformed(evt);
            }
        });

        set11chpts.setColumns(5);
        set11chpts.setText("0");

        jLabel1.setText(":");

        set11capts.setColumns(5);
        set11capts.setText("0");
        set11capts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set11captsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addComponent(set11chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set11capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set11chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(set11capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel2Layout = new javax.swing.GroupLayout(gamePanel2);
        gamePanel2.setLayout(gamePanel2Layout);
        gamePanel2Layout.setHorizontalGroup(
            gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel2Layout.createSequentialGroup()
                .addComponent(set11bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set11bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel2Layout.setVerticalGroup(
            gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel2Layout.createSequentialGroup()
                .addGroup(gamePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set11bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(set11bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel1Layout = new javax.swing.GroupLayout(gamePanel1);
        gamePanel1.setLayout(gamePanel1Layout);
        gamePanel1Layout.setHorizontalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel1Layout.createSequentialGroup()
                .addComponent(set11ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set11aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(gamePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel1Layout.setVerticalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel1Layout.createSequentialGroup()
                .addGroup(gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set11ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(set11aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout setPanelLayout = new javax.swing.GroupLayout(setPanel);
        setPanel.setLayout(setPanelLayout);
        setPanelLayout.setHorizontalGroup(
            setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanelLayout.createSequentialGroup()
                .addComponent(set11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(setPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setPanelLayout.setVerticalGroup(
            setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanelLayout.createSequentialGroup()
                .addComponent(set11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDbl.setText("set number");

        dah.setColumns(5);
        dah.setText("0");

        jLabel4.setText(":");

        daa.setColumns(5);
        daa.setText("0");
        daa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daaActionPerformed(evt);
            }
        });

        dbh.setColumns(5);
        dbh.setText("0");

        jLabel5.setText(":");

        dba.setColumns(5);
        dba.setText("0");
        dba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbaActionPerformed(evt);
            }
        });

        dch.setColumns(5);
        dch.setText("0");
        dch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dchActionPerformed(evt);
            }
        });

        jLabel6.setText(":");

        dca.setColumns(5);
        dca.setText("0");
        dca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel5Layout = new javax.swing.GroupLayout(gamePanel5);
        gamePanel5.setLayout(gamePanel5Layout);
        gamePanel5Layout.setHorizontalGroup(
            gamePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel5Layout.createSequentialGroup()
                .addComponent(dch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gamePanel5Layout.setVerticalGroup(
            gamePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel5Layout.createSequentialGroup()
                .addGroup(gamePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel4Layout = new javax.swing.GroupLayout(gamePanel4);
        gamePanel4.setLayout(gamePanel4Layout);
        gamePanel4Layout.setHorizontalGroup(
            gamePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel4Layout.createSequentialGroup()
                .addComponent(dbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(gamePanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel4Layout.setVerticalGroup(
            gamePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel4Layout.createSequentialGroup()
                .addGroup(gamePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout gamePanel3Layout = new javax.swing.GroupLayout(gamePanel3);
        gamePanel3.setLayout(gamePanel3Layout);
        gamePanel3Layout.setHorizontalGroup(
            gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel3Layout.createSequentialGroup()
                .addComponent(dah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(gamePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel3Layout.setVerticalGroup(
            gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel3Layout.createSequentialGroup()
                .addGroup(gamePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(daa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel15.setText("double");

        javax.swing.GroupLayout setPanel1Layout = new javax.swing.GroupLayout(setPanel1);
        setPanel1.setLayout(setPanel1Layout);
        setPanel1Layout.setHorizontalGroup(
            setPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel1Layout.createSequentialGroup()
                .addComponent(setDbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(setPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setPanel1Layout.setVerticalGroup(
            setPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel1Layout.createSequentialGroup()
                .addGroup(setPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setDbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        set12.setText("set number");

        set12ahpts.setColumns(5);
        set12ahpts.setText("0");

        jLabel7.setText(":");

        set12aapts.setColumns(5);
        set12aapts.setText("0");
        set12aapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set12aaptsActionPerformed(evt);
            }
        });

        set12bhpts.setColumns(5);
        set12bhpts.setText("0");

        jLabel8.setText(":");

        set12bapts.setColumns(5);
        set12bapts.setText("0");
        set12bapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set12baptsActionPerformed(evt);
            }
        });

        set12chpts.setColumns(5);
        set12chpts.setText("0");

        jLabel9.setText(":");

        set12capts.setColumns(5);
        set12capts.setText("0");
        set12capts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set12captsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel8Layout = new javax.swing.GroupLayout(gamePanel8);
        gamePanel8.setLayout(gamePanel8Layout);
        gamePanel8Layout.setHorizontalGroup(
            gamePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel8Layout.createSequentialGroup()
                .addComponent(set12chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set12capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gamePanel8Layout.setVerticalGroup(
            gamePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel8Layout.createSequentialGroup()
                .addGroup(gamePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set12chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(set12capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel7Layout = new javax.swing.GroupLayout(gamePanel7);
        gamePanel7.setLayout(gamePanel7Layout);
        gamePanel7Layout.setHorizontalGroup(
            gamePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel7Layout.createSequentialGroup()
                .addComponent(set12bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set12bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(gamePanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel7Layout.setVerticalGroup(
            gamePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel7Layout.createSequentialGroup()
                .addGroup(gamePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set12bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(set12bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamePanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel6Layout = new javax.swing.GroupLayout(gamePanel6);
        gamePanel6.setLayout(gamePanel6Layout);
        gamePanel6Layout.setHorizontalGroup(
            gamePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel6Layout.createSequentialGroup()
                .addComponent(set12ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set12aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(gamePanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel6Layout.setVerticalGroup(
            gamePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel6Layout.createSequentialGroup()
                .addGroup(gamePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set12ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(set12aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout setPanel2Layout = new javax.swing.GroupLayout(setPanel2);
        setPanel2.setLayout(setPanel2Layout);
        setPanel2Layout.setHorizontalGroup(
            setPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel2Layout.createSequentialGroup()
                .addComponent(set12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(setPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setPanel2Layout.setVerticalGroup(
            setPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel2Layout.createSequentialGroup()
                .addComponent(set12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        set22.setText("set number");

        set22ahpts.setColumns(5);
        set22ahpts.setText("0");

        jLabel10.setText(":");

        set22aapts.setColumns(5);
        set22aapts.setText("0");
        set22aapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set22aaptsActionPerformed(evt);
            }
        });

        set22bhpts.setColumns(5);
        set22bhpts.setText("0");

        jLabel11.setText(":");

        set22bapts.setColumns(5);
        set22bapts.setText("0");
        set22bapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set22baptsActionPerformed(evt);
            }
        });

        set22chpts.setColumns(5);
        set22chpts.setText("0");
        set22chpts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set22chptsActionPerformed(evt);
            }
        });

        jLabel12.setText(":");

        set22capts.setColumns(5);
        set22capts.setText("0");
        set22capts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set22captsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel11Layout = new javax.swing.GroupLayout(gamePanel11);
        gamePanel11.setLayout(gamePanel11Layout);
        gamePanel11Layout.setHorizontalGroup(
            gamePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel11Layout.createSequentialGroup()
                .addComponent(set22chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set22capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gamePanel11Layout.setVerticalGroup(
            gamePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel11Layout.createSequentialGroup()
                .addGroup(gamePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set22chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(set22capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel10Layout = new javax.swing.GroupLayout(gamePanel10);
        gamePanel10.setLayout(gamePanel10Layout);
        gamePanel10Layout.setHorizontalGroup(
            gamePanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel10Layout.createSequentialGroup()
                .addComponent(set22bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set22bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(gamePanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel10Layout.setVerticalGroup(
            gamePanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel10Layout.createSequentialGroup()
                .addGroup(gamePanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set22bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(set22bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamePanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel9Layout = new javax.swing.GroupLayout(gamePanel9);
        gamePanel9.setLayout(gamePanel9Layout);
        gamePanel9Layout.setHorizontalGroup(
            gamePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel9Layout.createSequentialGroup()
                .addComponent(set22ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set22aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addComponent(gamePanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel9Layout.setVerticalGroup(
            gamePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel9Layout.createSequentialGroup()
                .addGroup(gamePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set22ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(set22aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout setPanel3Layout = new javax.swing.GroupLayout(setPanel3);
        setPanel3.setLayout(setPanel3Layout);
        setPanel3Layout.setHorizontalGroup(
            setPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel3Layout.createSequentialGroup()
                .addComponent(set22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(setPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setPanel3Layout.setVerticalGroup(
            setPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel3Layout.createSequentialGroup()
                .addComponent(set22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setText("Home Win");

        jLabel19.setText("Away win");

        setPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        set21.setText("set number");

        set21ahpts.setColumns(5);
        set21ahpts.setText("0");

        jLabel14.setText(":");

        set21aapts.setColumns(5);
        set21aapts.setText("0");
        set21aapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set21aaptsActionPerformed(evt);
            }
        });

        set21bhpts.setColumns(5);
        set21bhpts.setText("0");

        jLabel20.setText(":");

        set21bapts.setColumns(5);
        set21bapts.setText("0");
        set21bapts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set21baptsActionPerformed(evt);
            }
        });

        set21chpts.setColumns(5);
        set21chpts.setText("0");

        jLabel21.setText(":");

        set21capts.setColumns(5);
        set21capts.setText("0");
        set21capts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set21captsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel14Layout = new javax.swing.GroupLayout(gamePanel14);
        gamePanel14.setLayout(gamePanel14Layout);
        gamePanel14Layout.setHorizontalGroup(
            gamePanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel14Layout.createSequentialGroup()
                .addComponent(set21chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set21capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gamePanel14Layout.setVerticalGroup(
            gamePanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel14Layout.createSequentialGroup()
                .addGroup(gamePanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set21chpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(set21capts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel13Layout = new javax.swing.GroupLayout(gamePanel13);
        gamePanel13.setLayout(gamePanel13Layout);
        gamePanel13Layout.setHorizontalGroup(
            gamePanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel13Layout.createSequentialGroup()
                .addComponent(set21bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set21bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(gamePanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel13Layout.setVerticalGroup(
            gamePanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel13Layout.createSequentialGroup()
                .addGroup(gamePanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set21bhpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(set21bapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamePanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanel12Layout = new javax.swing.GroupLayout(gamePanel12);
        gamePanel12.setLayout(gamePanel12Layout);
        gamePanel12Layout.setHorizontalGroup(
            gamePanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel12Layout.createSequentialGroup()
                .addComponent(set21ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(set21aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addComponent(gamePanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanel12Layout.setVerticalGroup(
            gamePanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanel12Layout.createSequentialGroup()
                .addGroup(gamePanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set21ahpts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(set21aapts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout setPanel4Layout = new javax.swing.GroupLayout(setPanel4);
        setPanel4.setLayout(setPanel4Layout);
        setPanel4Layout.setHorizontalGroup(
            setPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel4Layout.createSequentialGroup()
                .addComponent(set21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(setPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        setPanel4Layout.setVerticalGroup(
            setPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanel4Layout.createSequentialGroup()
                .addComponent(set21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setText("Final score:");

        aPlayer1.setText("jin");
        aPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPlayer1ActionPerformed(evt);
            }
        });

        aPlayer2.setText("julia");
        aPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPlayer2ActionPerformed(evt);
            }
        });

        hPlayer1.setText("alex");
        hPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hPlayer1ActionPerformed(evt);
            }
        });

        hPlayer2.setText("brian");
        hPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hPlayer2ActionPerformed(evt);
            }
        });

        calScorebutton.setText("Calculate scores");
        calScorebutton.setEnabled(false);
        calScorebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calScorebuttonActionPerformed(evt);
            }
        });

        hdblplayer1.setText("alex");

        hdblplayer2.setText("brian");

        adblplayer1.setText("jin");

        adblplayer2.setText("julia");

        jLabel13.setText("home players");

        hWinRow1.setText("Home player");
        hWinRow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        doubleHWin.setText("Home player");
        doubleHWin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hWinTotal.setText("home");
        hWinTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hWinRow2.setText("Home player");
        hWinRow2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        aWinRow1.setText("Away player");
        aWinRow1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        aWinRow2.setText("Away player");
        aWinRow2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        doubleAWin.setText("Away player");
        doubleAWin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        aWinTotal.setText("away");
        aWinTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        submitScoreButton.setText("Submit scores");
        submitScoreButton.setEnabled(false);
        submitScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitScoreButtonActionPerformed(evt);
            }
        });

        newMatchButton.setText("check player names");
        newMatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMatchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel100Layout = new javax.swing.GroupLayout(jPanel100);
        jPanel100.setLayout(jPanel100Layout);
        jPanel100Layout.setHorizontalGroup(
            jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel100Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel100Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(aPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(aPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(jPanel100Layout.createSequentialGroup()
                        .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel100Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel100Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hPlayer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hPlayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel100Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addComponent(setPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(setPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel100Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel100Layout.createSequentialGroup()
                                        .addComponent(setPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(setPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addComponent(doubleHWin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(doubleAWin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addComponent(hWinTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(aWinTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addComponent(hWinRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(aWinRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addComponent(hWinRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(aWinRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel100Layout.createSequentialGroup()
                                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel100Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(hdblplayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hdblplayer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel100Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(adblplayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(adblplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(35, 35, 35)
                                        .addComponent(setPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel100Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(newMatchButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(calScorebutton)
                                        .addGap(18, 18, 18)
                                        .addComponent(submitScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(37, 37, 37))
        );
        jPanel100Layout.setVerticalGroup(
            jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel100Layout.createSequentialGroup()
                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(aPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel100Layout.createSequentialGroup()
                        .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(setPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel100Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hWinRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aWinRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(setPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hPlayer2))
                            .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hWinRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aWinRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel100Layout.createSequentialGroup()
                                .addComponent(hdblplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hdblplayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adblplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adblplayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(setPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doubleHWin, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(jPanel100Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(doubleAWin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(hWinTotal)
                    .addComponent(aWinTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitScoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calScorebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newMatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        hTeamName.setText("home team name ");

        aTeamName.setText("away team name");

        jLabel22.setText("vs");

        hTeamField.setText("filton");
        hTeamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hTeamFieldActionPerformed(evt);
            }
        });

        aTeamField.setText("uwe");
        aTeamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTeamFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("away players");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        testScoreButton.setBackground(new java.awt.Color(0, 0, 0));
        testScoreButton.setForeground(new java.awt.Color(255, 51, 0));
        testScoreButton.setText("Generate Test Scores");
        testScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testScoreButtonActionPerformed(evt);
            }
        });

        allTeamButton.setText("List all teams");
        allTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTeamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(hTeamName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addGap(12, 12, 12)
                                .addComponent(aTeamName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testScoreButton)
                            .addComponent(allTeamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hTeamName)
                    .addComponent(hTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(aTeamName)
                    .addComponent(aTeamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //  Action methods for all point entry boxes
    private void set11captsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set11captsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set11captsActionPerformed

    private void set11aaptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set11aaptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set11aaptsActionPerformed

    private void set11baptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set11baptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set11baptsActionPerformed

    private void daaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daaActionPerformed

    private void dbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbaActionPerformed

    private void dcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dcaActionPerformed

    private void set12aaptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set12aaptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set12aaptsActionPerformed

    private void set12baptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set12baptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set12baptsActionPerformed

    private void set12captsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set12captsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set12captsActionPerformed

    private void set22aaptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set22aaptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set22aaptsActionPerformed

    private void set22baptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set22baptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set22baptsActionPerformed

    private void set22captsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set22captsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set22captsActionPerformed

    private void set21aaptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set21aaptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set21aaptsActionPerformed

    private void set21baptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set21baptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set21baptsActionPerformed

    private void set21captsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set21captsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set21captsActionPerformed

    private void set11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set11ActionPerformed

    // Action methods for players and teams
    private void hPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hPlayer1ActionPerformed

    private void hTeamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hTeamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hTeamFieldActionPerformed

    private void aTeamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTeamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTeamFieldActionPerformed

    private void aPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPlayer2ActionPerformed

    private void hPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hPlayer2ActionPerformed

    private void aPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPlayer1ActionPerformed

    // Action methods for buttons
    private void calScorebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calScorebuttonActionPerformed
        GameScore[] games = new GameScore[15]; // Declare array of games
        for(int i = 0; i < games.length; i++) { // Initialize array of games
            games[i] = new GameScore();
        }
        
        // Declare and initialize the double set
        DoubleSet setd = new DoubleSet((Integer.parseInt(setDbl.getText())), mgr.getTeam(hTeamField.getText()).getPlayer(hdblplayer1.getText()), mgr.getTeam(hTeamField.getText()).getPlayer(hdblplayer2.getText()), mgr.getTeam(aTeamField.getText()).getPlayer(adblplayer1.getText()), mgr.getTeam(aTeamField.getText()).getPlayer(adblplayer2.getText()));
        boolean[] winners = new boolean[20]; // Declare and initialize array of booleans for calculateHomeGameWin & calculateHomeSetWin methods
        
        // Calculate game winners for set 1
        winners[0] = games[0].calculateHomeGameWin(Integer.parseInt(set11ahpts.getText()), Integer.parseInt(set11aapts.getText()));
        winners[1] = games[1].calculateHomeGameWin(Integer.parseInt(set11bhpts.getText()), Integer.parseInt(set11bapts.getText()));
        winners[2] = games[2].calculateHomeGameWin(Integer.parseInt(set11chpts.getText()), Integer.parseInt(set11capts.getText()));
        SingleSet s1 = new SingleSet(Integer.parseInt(set11.getText()));
        winners[3] = s1.calculateHomeSetWin(winners[0], winners[1], winners[2]); // Calculate set 1 winner
        
        // Calculate game winners for set 2
        winners[4] = games[3].calculateHomeGameWin(Integer.parseInt(set12ahpts.getText()), Integer.parseInt(set12aapts.getText()));
        winners[5] = games[4].calculateHomeGameWin(Integer.parseInt(set12bhpts.getText()), Integer.parseInt(set12bapts.getText()));
        winners[6] = games[5].calculateHomeGameWin(Integer.parseInt(set12chpts.getText()), Integer.parseInt(set12capts.getText()));
        SingleSet s2 = new SingleSet(Integer.parseInt(set12.getText()));
        winners[7] = s2.calculateHomeSetWin(winners[4], winners[5], winners[6]); // Calculate set 2 winner
        
        // Calculate game winners for set 3
        winners[8] = games[6].calculateHomeGameWin(Integer.parseInt(set21ahpts.getText()), Integer.parseInt(set21aapts.getText()));
        winners[9] = games[7].calculateHomeGameWin(Integer.parseInt(set21bhpts.getText()), Integer.parseInt(set21bapts.getText()));
        winners[10] = games[8].calculateHomeGameWin(Integer.parseInt(set21chpts.getText()), Integer.parseInt(set21capts.getText()));
        SingleSet s3 = new SingleSet(Integer.parseInt(set21.getText()));
        winners[11] = s3.calculateHomeSetWin(winners[8], winners[9], winners[10]); // Calculate set 3 winner
        
        // Calculate game winners for set 4
        winners[12] = games[9].calculateHomeGameWin(Integer.parseInt(set22ahpts.getText()), Integer.parseInt(set22aapts.getText()));
        winners[13] = games[10].calculateHomeGameWin(Integer.parseInt(set22bhpts.getText()), Integer.parseInt(set22bapts.getText()));
        winners[14] = games[11].calculateHomeGameWin(Integer.parseInt(set22chpts.getText()), Integer.parseInt(set22capts.getText()));
        SingleSet s4 = new SingleSet(Integer.parseInt(set22.getText()));
        winners[15] = s4.calculateHomeSetWin(winners[12], winners[13], winners[14]); // Calculate set 4 winner
        
        // Calculate game winners for double set
        winners[16] = games[12].calculateHomeGameWin(Integer.parseInt(dah.getText()), Integer.parseInt(daa.getText()));
        winners[17] = games[13].calculateHomeGameWin(Integer.parseInt(dbh.getText()), Integer.parseInt(dba.getText()));
        winners[18] = games[14].calculateHomeGameWin(Integer.parseInt(dch.getText()), Integer.parseInt(dca.getText()));
        winners[19] = setd.calculateHomeSetWin(winners[16], winners[17], winners[18]); // Calculate double set winner
        
        // DEBUG
        // System.out.println(set1HWin + "\n" + set2HWin + "\n" + set3HWin + "\n" + set4HWin + "\n" + setdHWin);
        
        // Calculate overall match scores
        MatchScore match = new MatchScore(mgr.getTeam(hTeamField.getText()), mgr.getTeam(aTeamField.getText()), (mgr.getTeam(hTeamField.getText()).getPlayer(hPlayer1.getText())), (mgr.getTeam(hTeamField.getText()).getPlayer(hPlayer2.getText())), (mgr.getTeam(aTeamField.getText()).getPlayer(aPlayer1.getText())), (mgr.getTeam(aTeamField.getText()).getPlayer(aPlayer1.getText())));
        int[] totals = match.calculateMatchWin(winners[3], winners[7], winners[11], winners[15], winners[19]);
        
        // Output overall scores
        hWinRow1.setText(Integer.toString(match.getRow1Home()));
        aWinRow1.setText(Integer.toString(match.getRow1Away()));
        hWinRow2.setText(Integer.toString(match.getRow2Home()));
        aWinRow2.setText(Integer.toString(match.getRow2Away()));
        doubleHWin.setText(Integer.toString(match.getRowdHome()));
        doubleAWin.setText(Integer.toString(match.getRowdAway()));
        hWinTotal.setText(Integer.toString(totals[0]));
        aWinTotal.setText(Integer.toString(totals[1]));
        
        // Submit scores
        mgr.getTeam(hTeamField.getText()).addPts(totals[0]);
        mgr.getTeam(aTeamField.getText()).addPts(totals[1]);
        
        // Enable submit scores button
        submitScoreButton.setEnabled(true);
    }//GEN-LAST:event_calScorebuttonActionPerformed

    private void set22chptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set22chptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set22chptsActionPerformed

    private void dchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dchActionPerformed

    private void submitScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitScoreButtonActionPerformed
        // complete submission of scoresheet by disabling calculate scores and submit scores buttons, returning to step 1
        calScorebutton.setEnabled(false);
        submitScoreButton.setEnabled(false);
    }//GEN-LAST:event_submitScoreButtonActionPerformed

    private void allTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTeamButtonActionPerformed
        JOptionPane.showMessageDialog(null, mgr.getAllTeams()); // print all teams that exist with a non-zero totalPtsWon value
    }//GEN-LAST:event_allTeamButtonActionPerformed
    
    private void newMatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMatchButtonActionPerformed
        mgr.addTeam("filton", "gloucester road");
        mgr.addTeam("uwe", "frenchay campus");
        mgr.addTeam("kcc", "fortfield road");
        mgr.addTeam("page", "page road");
        mgr.teamList.get(0).addMember(null, "alex");
        mgr.teamList.get(0).addMember(null, "brian");
        mgr.teamList.get(1).addMember(null, "jin");
        mgr.teamList.get(1).addMember(null, "julia");
        mgr.teamList.get(2).addMember(null, "chris");
        mgr.teamList.get(2).addMember(null, "ryan");
        mgr.teamList.get(3).addMember(null, "peter");
        mgr.teamList.get(3).addMember(null, "phil");
        
        boolean[] validity = new boolean[8]; // home players, overall home, away players, overall away, double players
        
        for (Player i : mgr.getTeam(hTeamField.getText()).playerList) { // check home player's existence in corresponding team's playerList
            if (mgr.getTeam(hTeamField.getText()).getPlayer(hPlayer1.getText()) == i) validity[0] = true;
            if (mgr.getTeam(hTeamField.getText()).getPlayer(hPlayer2.getText()) == i) validity[1] = true;            
        }
        if (validity[0] && validity[1]) validity[2] = true; // set home validity to true if both home players valid
        
        for (Player i : mgr.getTeam(aTeamField.getText()).playerList) { // check away player's existence in corresponding team's playerList
            if (mgr.getTeam(aTeamField.getText()).getPlayer(aPlayer1.getText()) == i) validity[3] = true;
            if (mgr.getTeam(aTeamField.getText()).getPlayer(aPlayer2.getText()) == i) validity[4] = true;            
        }
        if (validity[3] && validity[4]) validity[5] = true; // set away validity to true if both away players valid
        
        // check double player's existence in corresponding team's playerList
        if (hPlayer1.getText().equals(hdblplayer1.getText()) && hPlayer2.getText().equals(hdblplayer2.getText())) validity[6] = true;
        if (aPlayer1.getText().equals(adblplayer1.getText()) && aPlayer2.getText().equals(adblplayer2.getText())) validity[7] = true;
        
        // display relevant error messages
        if (validity[2] == false) JOptionPane.showMessageDialog(null, "Error - home team doesn't exist or players entered incorrectly!");
        if (validity[5] == false) JOptionPane.showMessageDialog(null, "Error - away team doesn't exist or players entered incorrectly!");
        if (validity[6] == false) JOptionPane.showMessageDialog(null, "Error - home double players don't match home single players!");
        if (validity[7] == false) JOptionPane.showMessageDialog(null, "Error - away double players don't match away single players!");
        if (validity[2] && validity[5] && validity[6] && validity[7]) { // if all players validity is verified, enable calculate score button
            calScorebutton.setEnabled(true);
        }
    }//GEN-LAST:event_newMatchButtonActionPerformed

    private void set11ahptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set11ahptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_set11ahptsActionPerformed

    // Action method for Generate Scores button
    private void testScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testScoreButtonActionPerformed
        if (!sc.hasNext())
            return;
        else {
            set11ahpts.setText(sc.nextInt() + "");
            set11aapts.setText(sc.nextInt() + "");
            set11bhpts.setText(sc.nextInt() + "");
            set11bapts.setText(sc.nextInt() + "");
            set11chpts.setText(sc.nextInt() + "");
            set11capts.setText(sc.nextInt() + "");

            set12ahpts.setText(sc.nextInt() + "");
            set12aapts.setText(sc.nextInt() + "");
            set12bhpts.setText(sc.nextInt() + "");
            set12bapts.setText(sc.nextInt() + "");
            set12chpts.setText(sc.nextInt() + "");
            set12capts.setText(sc.nextInt() + "");

            set21ahpts.setText(sc.nextInt() + "");
            set21aapts.setText(sc.nextInt() + "");
            set21bhpts.setText(sc.nextInt() + "");
            set21bapts.setText(sc.nextInt() + "");
            set21chpts.setText(sc.nextInt() + "");
            set21capts.setText(sc.nextInt() + "");

            set22ahpts.setText(sc.nextInt() + "");
            set22aapts.setText(sc.nextInt() + "");
            set22bhpts.setText(sc.nextInt() + "");
            set22bapts.setText(sc.nextInt() + "");
            set22chpts.setText(sc.nextInt() + "");
            set22capts.setText(sc.nextInt() + "");

            dah.setText(sc.nextInt() + "");
            daa.setText(sc.nextInt() + "");
            dbh.setText(sc.nextInt() + "");
            dba.setText(sc.nextInt() + "");
            dch.setText(sc.nextInt() + "");
            dca.setText(sc.nextInt() + "");
            sc.nextLine();
            
            set11.setText(Integer.toString(1));
            set12.setText(Integer.toString(2));
            set21.setText(Integer.toString(3));
            set22.setText(Integer.toString(4));
            setDbl.setText(Integer.toString(5));     
    }//GEN-LAST:event_testScoreButtonActionPerformed
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTScoreGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTScoreGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTScoreGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTScoreGUI1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTScoreGUI1().setVisible(true);
            }
        });
    }
    
    // Variables:
    RegistrationManager mgr = new RegistrationManager();
    public Scanner sc = new Scanner(TTScoreGUI1.class.getResourceAsStream("/testscores.txt"));
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aPlayer1;
    private javax.swing.JTextField aPlayer2;
    private javax.swing.JTextField aTeamField;
    private javax.swing.JLabel aTeamName;
    private javax.swing.JLabel aWinRow1;
    private javax.swing.JLabel aWinRow2;
    private javax.swing.JLabel aWinTotal;
    private javax.swing.JTextField adblplayer1;
    private javax.swing.JTextField adblplayer2;
    private javax.swing.JButton allTeamButton;
    private javax.swing.JButton calScorebutton;
    private javax.swing.JTextField daa;
    private javax.swing.JTextField dah;
    private javax.swing.JTextField dba;
    private javax.swing.JTextField dbh;
    private javax.swing.JTextField dca;
    private javax.swing.JTextField dch;
    private javax.swing.JLabel doubleAWin;
    private javax.swing.JLabel doubleHWin;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel gamePanel1;
    private javax.swing.JPanel gamePanel10;
    private javax.swing.JPanel gamePanel11;
    private javax.swing.JPanel gamePanel12;
    private javax.swing.JPanel gamePanel13;
    private javax.swing.JPanel gamePanel14;
    private javax.swing.JPanel gamePanel2;
    private javax.swing.JPanel gamePanel3;
    private javax.swing.JPanel gamePanel4;
    private javax.swing.JPanel gamePanel5;
    private javax.swing.JPanel gamePanel6;
    private javax.swing.JPanel gamePanel7;
    private javax.swing.JPanel gamePanel8;
    private javax.swing.JPanel gamePanel9;
    private javax.swing.JTextField hPlayer1;
    private javax.swing.JTextField hPlayer2;
    private javax.swing.JTextField hTeamField;
    private javax.swing.JLabel hTeamName;
    private javax.swing.JLabel hWinRow1;
    private javax.swing.JLabel hWinRow2;
    private javax.swing.JLabel hWinTotal;
    private javax.swing.JTextField hdblplayer1;
    private javax.swing.JTextField hdblplayer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JButton newMatchButton;
    private javax.swing.JTextField set11;
    private javax.swing.JTextField set11aapts;
    private javax.swing.JTextField set11ahpts;
    private javax.swing.JTextField set11bapts;
    private javax.swing.JTextField set11bhpts;
    private javax.swing.JTextField set11capts;
    private javax.swing.JTextField set11chpts;
    private javax.swing.JTextField set12;
    private javax.swing.JTextField set12aapts;
    private javax.swing.JTextField set12ahpts;
    private javax.swing.JTextField set12bapts;
    private javax.swing.JTextField set12bhpts;
    private javax.swing.JTextField set12capts;
    private javax.swing.JTextField set12chpts;
    private javax.swing.JTextField set21;
    private javax.swing.JTextField set21aapts;
    private javax.swing.JTextField set21ahpts;
    private javax.swing.JTextField set21bapts;
    private javax.swing.JTextField set21bhpts;
    private javax.swing.JTextField set21capts;
    private javax.swing.JTextField set21chpts;
    private javax.swing.JTextField set22;
    private javax.swing.JTextField set22aapts;
    private javax.swing.JTextField set22ahpts;
    private javax.swing.JTextField set22bapts;
    private javax.swing.JTextField set22bhpts;
    private javax.swing.JTextField set22capts;
    private javax.swing.JTextField set22chpts;
    private javax.swing.JTextField setDbl;
    private javax.swing.JPanel setPanel;
    private javax.swing.JPanel setPanel1;
    private javax.swing.JPanel setPanel2;
    private javax.swing.JPanel setPanel3;
    private javax.swing.JPanel setPanel4;
    private javax.swing.JButton submitScoreButton;
    private javax.swing.JButton testScoreButton;
    // End of variables declaration//GEN-END:variables
}
